### ISSUE TITLE
Добавить почтовый индекс

### ISSUE THREAD

**Issue by pttsky** [SilverFire/7-info#9]
Вопрос уже пару раз повторялся в чате. Просится в базу знаний.

**Comment by SilverFire** [comment]
Індекс: 02095

Адреса: вул. Срібнокільська, 24

Населений пункт: Київ

Телефон: 044 574 84 92

Час роботи:

понеділок-п'ятниця: 9:00 - 19:00 (Перерва: 14:00 - 15:00)
субота: 9:00 - 17:00 (Перерва: 14:00 - 15:00)
